---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-reader
rules:
  # Limit user to read pods API
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
