name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Triggers the workflow when pushing to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image, specifying the correct path to Dockerfile
      - name: Build Docker image
        run: docker build -t hadas2408/k8s-service-a:latest -f Docker/serviceA/Dockerfile Docker/serviceA/

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push hadas2408/k8s-service-a:latest
